spring.application.name=backend

sever.adress=0.0.0.0
sever.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/puntoVenta
spring.datasource.username=root
spring.datasource.password=Malboro00

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect








